AtlDrag/urls.py
from django.contrib import admin
from django.urls import path
from drag.views import * 

urlpatterns = [
    path('admin/', admin.site.urls),

    path('move_customer/', move_customer, name='move_customer'),
    path('index/', index, name='index'),
    path('table/', table_view, name='table_view'),
    path('edit/<int:pk>/', edit_row, name='edit_row'),
    path("add/",add_formdata , name="add"),
    path("save/",add_row , name = "save"),
    path("submit-form/", addNewEntry , name='submit-form'),
    path("search/",Search , name='Search'),
    path("list/",list_hystory , name='list'),
    path("login/",login_view, name="login"),
    path('logout/',logout_view,name='logout'),
    path("runquery/",runquery, name="runquery")
]

drag/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100 ,null=True, blank=True)
    margin = models.CharField(max_length=100 ,null=True, blank=True)

    def __str__(self):
        return self.name

class Customer(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Freight_Rate(models.Model):
    POL = models.CharField(max_length=100,null=True, blank=True)
    POD = models.CharField(max_length=100,null=True, blank=True)
    LINER = models.CharField(max_length=100,null=True, blank=True)
    TYPE = models.CharField(max_length=100,null=True, blank=True)
    THC = models.CharField(max_length=100,null=True, blank=True)
    field6 = models.CharField(max_length=100,null=True, blank=True)
    CONTAINER = models.CharField(max_length=100,null=True, blank=True)
    field8 = models.CharField(max_length=100,null=True, blank=True)
    CONTAINER_PRICE = models.CharField(max_length=100,null=True, blank=True)
    SAEL_AMOUNT = models.CharField(max_length=100,null=True, blank=True)
    FREE_FEE = models.CharField(max_length=100,null=True, blank=True)
    FREE_DAYS = models.CharField(max_length=100,null=True, blank=True)
    VALIDITY_FROM = models.CharField(max_length=100,null=True, blank=True)
    VALIDITY_TO = models.CharField(max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    def has_expired(self):
        """
        Check if the record has expired based on its date field.
        """
        current_date = datetime.now().date()
        # Convert self.date to datetime.date object if it's stored as a string
        record_date = datetime.strptime(self.date, '%d-%m-%Y').date() if isinstance(self.date, str) else self.date
        return record_date < current_date

class Customercategory(models.Model):
    id = models.BigAutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    categorynameeng = models.CharField(db_column='CategoryNameEng', max_length=100)  # Field name made lowercase.
    categorynamejpn = models.CharField(db_column='CategoryNameJpn', max_length=255)  # Field name made lowercase.
    margin = models.IntegerField(db_column='Margin', blank=True, null=True)  # Field name made lowercase.
    createddatetimeutc = models.DateTimeField(db_column='CreatedDateTimeUtc')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=250)  # Field name made lowercase.
    updateddatetimeutc = models.DateTimeField(db_column='UpdatedDateTimeUtc')  # Field name made lowercase.
    updatedby = models.CharField(db_column='UpdatedBy', max_length=250)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CustomerCategory'

class Country(models.Model):
    id = models.BigAutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    countrynameeng = models.CharField(db_column='CountryNameEng', max_length=255, blank=True, null=True)  # Field name made lowercase.
    countrynamejpn = models.CharField(db_column='CountryNameJpn', max_length=255, blank=True, null=True)  # Field name made lowercase.
    uppercode = models.CharField(db_column='UpperCode', max_length=255, blank=True, null=True)  # Field name made lowercase.
    lowercode = models.CharField(db_column='LowerCode', max_length=255, blank=True, null=True)  # Field name made lowercase.
    nacsscountryid = models.CharField(db_column='NacssCountryId', max_length=2, blank=True, null=True)  # Field name made lowercase.
    uncode = models.CharField(db_column='UnCode', max_length=10, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Country'

class Customercompany(models.Model):
    id = models.BigAutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    companycountryid = models.ForeignKey(Country, models.CASCADE, db_column='CompanyCountryId')  # Field name made lowercase.
    companynameeng = models.CharField(db_column='CompanyNameEng', unique=True, max_length=100)  # Field name made lowercase.
    companynamejpn = models.CharField(db_column='CompanyNameJpn', unique=True, max_length=255)  # Field name made lowercase.
    primarypepresentative = models.CharField(db_column='PrimaryPepresentative', max_length=100)  # Field name made lowercase.
    secondarypepresentative = models.CharField(db_column='SecondaryPepresentative', max_length=100, blank=True, null=True)  # Field name made lowercase.
    officepostbox = models.CharField(db_column='OfficePostBox', max_length=20)  # Field name made lowercase.
    officeprefectureeng = models.CharField(db_column='OfficePrefectureEng', max_length=100)  # Field name made lowercase.
    officeprefecturejpn = models.CharField(db_column='OfficePrefectureJpn', max_length=100)  # Field name made lowercase.
    officecityeng = models.CharField(db_column='OfficeCityEng', max_length=100)  # Field name made lowercase.
    officecityjpn = models.CharField(db_column='OfficeCityJpn', max_length=100)  # Field name made lowercase.
    officeaddresseng = models.CharField(db_column='OfficeAddressEng', max_length=500)  # Field name made lowercase.
    officeaddressjpn = models.CharField(db_column='OfficeAddressJpn', max_length=500)  # Field name made lowercase.
    officephone = models.CharField(db_column='OfficePhone', unique=True, max_length=255)  # Field name made lowercase.
    officefax = models.CharField(db_column='OfficeFax', unique=True, max_length=255)  # Field name made lowercase.
    custompostbox = models.CharField(db_column='CustomPostBox', max_length=20)  # Field name made lowercase.
    customprefectureeng = models.CharField(db_column='CustomPrefectureEng', max_length=100)  # Field name made lowercase.
    customprefecturejpn = models.CharField(db_column='CustomPrefectureJpn', max_length=100)  # Field name made lowercase.
    customcityeng = models.CharField(db_column='CustomCityEng', max_length=100)  # Field name made lowercase.
    customcityjpn = models.CharField(db_column='CustomCityJpn', max_length=100)  # Field name made lowercase.
    customaddresseng = models.CharField(db_column='CustomAddressEng', max_length=500)  # Field name made lowercase.
    customaddressjpn = models.CharField(db_column='CustomAddressJpn', max_length=500)  # Field name made lowercase.
    iecode = models.CharField(db_column='IECode', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mailingpostbox = models.CharField(db_column='MailingPostBox', max_length=20)  # Field name made lowercase.
    mailingprefectureeng = models.CharField(db_column='MailingPrefectureEng', max_length=100)  # Field name made lowercase.
    mailingprefecturejpn = models.CharField(db_column='MailingPrefectureJpn', max_length=100)  # Field name made lowercase.
    mailingcityeng = models.CharField(db_column='MailingCityEng', max_length=100)  # Field name made lowercase.
    mailingcityjpn = models.CharField(db_column='MailingCityJpn', max_length=100)  # Field name made lowercase.
    mailingaddresseng = models.CharField(db_column='MailingAddressEng', max_length=500)  # Field name made lowercase.
    mailingaddressjpn = models.CharField(db_column='MailingAddressJpn', max_length=500)  # Field name made lowercase.
    companyremarks = models.TextField(db_column='CompanyRemarks', blank=True, null=True)  # Field name made lowercase.
    picturestoclick = models.CharField(db_column='PicturesToClick', max_length=250)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    createddatetimeutc = models.DateTimeField(db_column='CreatedDateTimeUtc')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=250)  # Field name made lowercase.
    updateddatetimeutc = models.DateTimeField(db_column='UpdatedDateTimeUtc')  # Field name made lowercase.
    updatedby = models.CharField(db_column='UpdatedBy', max_length=250)  # Field name made lowercase.
    customercategoryid = models.ForeignKey(Customercategory, models.CASCADE, db_column='CustomerCategoryId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CustomerCompany'

class Port(models.Model):
    id = models.BigAutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    portnameeng = models.CharField(db_column='PortNameEng', unique=True, max_length=100)  # Field name made lowercase.
    portnamejpn = models.CharField(db_column='PortNameJpn', unique=True, max_length=100)  # Field name made lowercase.
    portcountryid = models.ForeignKey('Country', models.DO_NOTHING, db_column='PortCountryId')  # Field name made lowercase.
    naccsportcode = models.CharField(db_column='NaccsPortCode', max_length=10, blank=True, null=True)  # Field name made lowercase.
    naccsstandardcode = models.CharField(db_column='NaccsStandardCode', max_length=20, blank=True, null=True)  # Field name made lowercase.
    inttraportcode = models.CharField(db_column='InttraPortCode', max_length=255, blank=True, null=True)  # Field name made lowercase.
    createddatetimeutc = models.DateTimeField(db_column='CreatedDateTimeUtc')  # Field name made lowercase.
    createdby = models.CharField(db_column='CreatedBy', max_length=250)  # Field name made lowercase.
    updateddatetimeutc = models.DateTimeField(db_column='UpdatedDateTimeUtc')  # Field name made lowercase.
    updatedby = models.CharField(db_column='UpdatedBy', max_length=250)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Port'

class Shippingcontainersize(models.Model):
    id = models.BigAutoField(db_column='Id', primary_key=True)  # Field name made lowercase.

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="board">
        {% for category in categories %}
        
        <div class="column" id="category_{{ category.id }}">
            <div class="search-sort">
            <input type="text" class="category-search"  data-category="{{ category.id }}" placeholder="Search in {{ category.categorynameeng }}" onkeyup="searchCustomer(this)">
            <div class="arrow-button" onclick="toggleSort('{{ category.id }}')">
                <!-- Up and down arrow icons for sorting -->
                <i class="fas fa-arrow-up arrow-icon"></i>
                <i class="fas fa-arrow-down arrow-icon"></i>
            </div>
        </div>
            <div class="cust-cat">
                <div>
                    <h5 class="mb-4 cust-d cust-d1">{{ category.categorynameeng }}</h5>
                </div>
                <div>
                    <h5 class="cust-d cust-d2">Margin {{category.margin}}%</h5>
                </div>
                <!-- Search input for this category -->
                
            </div>
            <div class="customer-list" id="customer-list-{{ category.id }}">
                {% for customer in category.customercompany_set.all %}
                <div class="customer" id="customer_{{ customer.id }}" data-category="{{ category.id }}">
                    <div>
                        <div class="customer-details">
                            {{ customer.companynameeng }}</p>
                            <i class="fas fa-grip-lines"></i>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            setupDragAndDrop();

            // Reapply drag and drop after page reloads
            $(document).ajaxComplete(function() {
                setupDragAndDrop();
            });

            function setupDragAndDrop() {
                $(".customer").draggable({
                    revert: 'invalid',
                    helper: 'clone',
                    start: function(event, ui) {
                        $(this).addClass("dragged-customer");
                    },
                    stop: function(event, ui) {
                        $(this).removeClass("dragged-customer");
                    }
                });

                $(".column").droppable({
                    accept: '.customer',
                    drop: function (event, ui) {
                        var customer_id = ui.draggable.attr("id").split("_")[1];
                        var category_id = $(this).attr("id").split("_")[1];
                        var old_category_id = ui.draggable.data("category");
                        if (category_id != old_category_id) {
                            $.ajax({
                                url: '/move_customer/',
                                type: 'POST',
                                data: {
                                    'customer_id': customer_id,
                                    'category_id': category_id,
                                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                                },
                                success: function () {
                                    
                                    // Reload both the dropped customer's category and the dragged customer's category
                                    var droppedCategoryContainer = "#customer-list-" + category_id;
                                    var draggedCategoryContainer = "#customer-list-" + old_category_id;
                                    console.log("path checking",droppedCategoryContainer,draggedCategoryContainer)
                                    $(droppedCategoryContainer).load(window.location.href + " " + droppedCategoryContainer, function() {
                                        $("#" + customer_id).addClass("draggable-dropped");
                                        setTimeout(function() {
                                            $("#" + customer_id).removeClass("draggable-dropped");
                                        }, 1000); // Remove class after 1 second
                                    });
                                    console.log("check data")
                                    $(draggedCategoryContainer).load(window.location.href + " " + draggedCategoryContainer);
                                }
                            });
                        }
                    }
                });

                // Update column height dynamically based on customer count
            
            }

            function updateColumnHeight(category_id) {
                var column = $("#category_" + category_id);
                var customerList = $("#customer-list-" + category_id);
                var customerCount = customerList.children().length;
                var minHeight = 100;
                var height = Math.max(minHeight, customerCount * 70); // Adjust the height based on the number of customers
                column.css({
        'min-height': height + 'px',
    });
            }
        });
    </script>



<script>
    function searchCustomer(input) {
        var filter, categoryID, customerList, customers, customer, txtValue;
        filter = input.value.toUpperCase();
        categoryID = input.getAttribute("data-category");
        customerList = document.getElementById("customer-list-" + categoryID);
        customers = customerList.getElementsByClassName("customer");
        for (var i = 0; i < customers.length; i++) {
            customer = customers[i].getElementsByClassName("customer-details")[0];
            txtValue = customer.textContent || customer.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                customers[i].style.display = "";
            } else {
                customers[i].style.display = "none";
            }
        }
    }
</script>




<script>
    var ascending = true; // Initially sorting in ascending order

    function toggleSort(categoryId) {
        var order = ascending ? 'asc' : 'desc';
        sortCustomers(categoryId, order);
        ascending = !ascending; // Toggle the sorting order
    }

    function sortCustomers(categoryId, order) {
        // Get the customer list for the specified category
        var customerList = document.getElementById("customer-list-" + categoryId);
        var customers = customerList.getElementsByClassName("customer");

        // Convert HTMLCollection to Array for easier manipulation
        var customersArray = Array.from(customers);

        // Sort customers based on company name
        customersArray.sort(function(a, b) {
            var nameA = a.querySelector(".customer-details").textContent.trim().toLowerCase();
            var nameB = b.querySelector(".customer-details").textContent.trim().toLowerCase();
            if (order === 'asc') {
                return nameA.localeCompare(nameB);
            } else {
                return nameB.localeCompare(nameA);
            }
        });

        // Reorder customers in the customer list
        customerList.innerHTML = '';
        customersArray.forEach(function(customer) {
            customerList.appendChild(customer);
        });
    }

    function searchCustomer(input) {
        var filter, categoryID, customerList, customers, customer, txtValue;
        filter = input.value.toUpperCase();
        categoryID = input.getAttribute("data-category");
        customerList = document.getElementById("customer-list-" + categoryID);
        customers = customerList.getElementsByClassName("customer");
        for (var i = 0; i < customers.length; i++) {
            customer = customers[i].getElementsByClassName("customer-details")[0];
            txtValue = customer.textContent || customer.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                customers[i].style.display = "";
            } else {
                customers[i].style.display = "none";
            }
        }
    }
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login Form</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <style>
    body, html {
        height:100%;
        background: #1c1e21;
        overflow-x: hidden;
        font-family: 'Dosis', sans-serif;
    }

    .btn-larger {
        padding: 15px 40px !important;
        border:2px solid #F7CA18 !important;
        border-radius: 0px !important;
        text-transform: uppercase;
        font-family: 'Dosis', sans-serif;
        font-size: 18px;
        font-weight: 300;
        color: #F7CA18;
        background-color: transparent;
        -webkit-transition: all .6s;
        -moz-transition: all .6s;
        transition: all .6s;
    }

    .btn-larger:hover, .btn-larger:focus, .btn-larger:active, .btn-larger.active, .open .dropdown-toggle.btn-larger {
        border-color: #F7CA18;
        color: #fff;
        background-color: #F7CA18;
    }

    .btn-larger:active, .btn-larger.active, .open .dropdown-toggle.btn-larger {
        background-image: none;
    }

    .btn-larger.disabled, .btn-larger[disabled], fieldset[disabled] .btn-larger, .btn-larger.disabled:hover, .btn-larger[disabled]:hover, fieldset[disabled] .btn-larger:hover, .btn-larger.disabled:focus, .btn-larger[disabled]:focus, fieldset[disabled] .btn-larger:focus, .btn-larger.disabled:active, .btn-larger[disabled]:active, fieldset[disabled] .btn-larger:active, .btn-larger.disabled.active, .btn-larger[disabled].active, fieldset[disabled] .btn-larger.active {
        border-color: #AEA8D3;
        background-color: #AEA8D3;
    }

    .btn-larger .badge {
        color: #AEA8D3;
        background-color: #fff;
    }

    #form {
        color: #fff;
        background-attachment: scroll;
        background: #1c1e21 url("/static/img/ship_back.png"); 
        background-repeat: none;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        -o-background-size: cover;
        min-height:100%;
    }

    .form-group {
        margin-bottom: 0px;
        color: #FFF;
    }

    .form-group input, .form-group textarea {
        padding: 10px;
    }

    .form-group input.form-control {
        height: auto;
        background-color: rgba(237, 235, 250, 0.1);
        color: #FFF;
    }

    .form-control {
        border-radius: 0;
        border: 1px solid #fff;
    }

    .form-control:focus {
        border-color: #F7CA18;
        box-shadow: none;
    }

    ::-webkit-input-placeholder {
        text-transform: uppercase;
        font-family: 'Dosis', sans-serif;
        font-weight: 700;
        color: #bbb;
    }

    #login .form-group label {
        position: relative;
        -webkit-transform: translateY(35px);
        -ms-transform: translateY(35px);
        transform: translateY(35px);
        left: 10px;
        top: 0px;
        color: rgba(255, 255, 255, 0.5);
        -webkit-transition: all 0.25s ease;
        transition: all 0.25s ease;
        -webkit-backface-visibility: hidden;
        pointer-events: none;
        font-size: 12px;
        font-weight: 300
    }

    #login .form-group label .req {
        margin: 2px;
        color: #F7CA18;
    }

    #login .form-group label.active {
        -webkit-transform: translateY(0px);
        -ms-transform: translateY(0px);
        transform: translateY(0px);
        left: 2px;
        font-size: 12px;
    }

    #login .form-group label.active .req {
        opacity: 0;
    }

    .mrgn-30-top {
        margin-top: 30px
    }
    #userform {
    background: rgba(0,0,0,0.3); /* Black background with 80% opacity */
    margin: 20px auto;
    padding: 20px;
    border-radius: 5px;
    max-width: 600px; /* Added max-width for better presentation on larger screens */
}
.form-set{
    margin-top: 160px;
    margin-left: -80px;
}



  </style>
</head>
<body>
  <div id="form">
    <div class="container">
      <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-md-8 form-set col-md-offset-2">
        <div id="userform">
          <!-- <ul class="nav nav-tabs nav-justified" role="tablist">
            <li class="active"><a href="#login"  role="tab" data-toggle="tab">Log in</a></li>
          </ul> -->
          <div class="tab-content">
            <div class="tab-pane fade active in" id="login">
              <!-- <h2 class="text-uppercase text-center"> Log in</h2> -->
              <form id="login" method="post" action="/login/">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control" name="lemail" placeholder="username" id="email" required data-validation-required-message="Please enter your name address." autocomplete="off">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <input type="password" class="form-control" name="lpassword" placeholder="password" id="password" required data-validation-required-message="Please enter your password" autocomplete="off">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="mrgn-30-top">
                  <button type="submit" class="btn btn-larger btn-block">Log in</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

templates/oIndex.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">
        <div class="board">
            {% for category in categories %}
            <div class="column" id="category_{{ category.id }}">
                <div class="cust-cat">
                    <div>
                        <h5 class="mb-4 cust-d cust-d1">{{ category.name }}</h5>

                    </div>
                    <div>
                        <h5 class="cust-d cust-d2">{{category.margin}}</h5>
                    </div>
                </div>
                <div class="customer-list" id="customer-list-{{ category.id }}">
                    {% for customer in category.customer_set.all %}
                    <div class="customer" id="customer_{{ customer.id }}" data-category="{{ category.id }}">
                        <div>
                            <div class="customer-details">
                                {{ customer.name }}</p>
                                <i class="fas fa-grip-lines"></i>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            setupDragAndDrop();

            // Reapply drag and drop after page reloads
            $(document).ajaxComplete(function() {
                setupDragAndDrop();
            });

            function setupDragAndDrop() {
                $(".customer").draggable({
                    revert: 'invalid',
                    helper: 'clone',
                    start: function(event, ui) {
                        $(this).addClass("dragged-customer");
                    },
                    stop: function(event, ui) {
                        $(this).removeClass("dragged-customer");
                    }
                });

                $(".column").droppable({
                    accept: '.customer',
                    drop: function (event, ui) {
                        var customer_id = ui.draggable.attr("id").split("_")[1];
                        var category_id = $(this).attr("id").split("_")[1];
                        var old_category_id = ui.draggable.data("category");
                        if (category_id != old_category_id) {
                            $.ajax({
                                url: '/move_customer/',
                                type: 'POST',
                                data: {
                                    'customer_id': customer_id,
                                    'category_id': category_id,
                                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                                },
                                success: function () {
                                    
                                    // Reload both the dropped customer's category and the dragged customer's category
                                    var droppedCategoryContainer = "#customer-list-" + category_id;
                                    var draggedCategoryContainer = "#customer-list-" + old_category_id;
                                    console.log("path checking",droppedCategoryContainer,draggedCategoryContainer)
                                    $(droppedCategoryContainer).load(window.location.href + " " + droppedCategoryContainer, function() {
                                        $("#" + customer_id).addClass("draggable-dropped");
                                        setTimeout(function() {
                                            $("#" + customer_id).removeClass("draggable-dropped");
                                        }, 1000); // Remove class after 1 second
                                    });
                                    console.log("check data")
                                    $(draggedCategoryContainer).load(window.location.href + " " + draggedCategoryContainer);
                                }
                            });
                        }
                    }
                });

                // Update column height dynamically based on customer count
                $(".column").each(function() {
                    var category_id = $(this).attr("id").split("_")[1];
                    updateColumnHeight(category_id);
                });
            }

            function updateColumnHeight(category_id) {
                var column = $("#category_" + category_id);
                var customerList = $("#customer-list-" + category_id);
                var customerCount = customerList.children().length;
                var minHeight = 100;
                var height = Math.max(minHeight, customerCount * 70); // Adjust the height based on the number of customers
                column.css({
        'min-height': height + 'px',
    });
            }
        });
    </script>
{% endblock %}